'use client';
import {useState} from 'react';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import {ArrowUpRight,Check} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
const schema=z.object({name:z.string().trim().min(2,'Please enter your name.').max(100),email:z.string().trim().email('Please enter a valid email address.'),message:z.string().trim().min(20,'Tell me a little more (at least 20 characters).').max(4000,'Please keep your message under 4,000 characters.')});
type Values=z.infer<typeof schema>;
export function ContactForm(){const [ready,setReady]=useState(false);const {register,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema)});function submit(data:Values){const body=`Hi Ahmed,\n\n${data.message}\n\nFrom: ${data.name}\nEmail: ${data.email}`;window.location.href=`mailto:ahmedesmailofficial01@gmail.com?subject=${encodeURIComponent('Project inquiry from '+data.name)}&body=${encodeURIComponent(body)}`;setReady(true);}return <form className="contact-form" onSubmit={handleSubmit(submit)}><div className="form-row"><div><label htmlFor="name">Your name</label><Input id="name" required minLength={2} maxLength={100} autoComplete="name" placeholder="Jane Smith" {...register('name')} aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined}/>{errors.name&&<p className="form-error" id="name-error">{errors.name.message}</p>}</div><div><label htmlFor="email">Email address</label><Input id="email" required type="email" autoComplete="email" placeholder="jane@company.com" {...register('email')} aria-invalid={!!errors.email} aria-describedby={errors.email?'email-error':undefined}/>{errors.email&&<p className="form-error" id="email-error">{errors.email.message}</p>}</div></div><label htmlFor="message">What are you thinking of building?</label><Textarea id="message" required minLength={20} maxLength={4000} rows={4} placeholder="Tell me about your idea, goals, and timeline…" {...register('message')} aria-invalid={!!errors.message} aria-describedby={errors.message?'message-error':undefined}/>{errors.message&&<p className="form-error" id="message-error">{errors.message.message}</p>}<div className="form-bottom"><span>Opens your email app with your inquiry.<br/>Send it there to get in touch.</span><Button className="pill" type="submit">Let's build it <ArrowUpRight/></Button></div>{ready&&<p role="status" className="form-status"><Check size={18}/> Your email draft is ready. If no email app opened, write to ahmedesmailofficial01@gmail.com.</p>}</form>}
