'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Play,Video,ExternalLink,Code2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Project} from '@/lib/content';
export function resolveVideo(value?:string){if(!value)return null;if(/^[a-zA-Z0-9]{20,64}$/.test(value))return `https://www.loom.com/embed/${value}`;try{const url=new URL(value);if(url.protocol!=='https:')return null;if(['www.loom.com','loom.com'].includes(url.hostname)){const id=url.pathname.split('/').filter(Boolean).pop();return id&&/^[a-zA-Z0-9]+$/.test(id)?`https://www.loom.com/embed/${id}`:null;}if(['www.youtube-nocookie.com','www.youtube.com','player.vimeo.com'].includes(url.hostname)&&/^\/(embed|video)\//.test(url.pathname))return url.href;}catch{}return null;}
export function ProjectVideo({title,image,loomVideoId,color,large=false}:{title:string;image:string;loomVideoId?:string;color:string;large?:boolean}){const [play,setPlay]=useState(false);const src=resolveVideo(loomVideoId);return <div className={`video-cover ${large?'large':''}`} style={{'--project-color':color} as React.CSSProperties}>{play&&src?<iframe title={`${title} video walkthrough`} src={src} loading="lazy" allow="fullscreen; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<><img src={image} alt={`${title} illustrative cover`} width="1200" height="800" loading="lazy"/><div className="cover-shade"/><span className="cover-brand">{title}</span><span className="cover-label">{src?'PROJECT WALKTHROUGH':'PROJECT PREVIEW'}</span>{src?<Button className="play-button" aria-label={`Play ${title} walkthrough`} onClick={()=>setPlay(true)}><Play size={20} fill="currentColor"/></Button>:<span className="video-soon"><Video size={15}/> Walkthrough coming soon</span>}<span className="cover-caption">DESIGNED TO WORK.<br/>BUILT TO FEEL DIFFERENT.</span></>}</div>}
export function VideoProjectCard({title,description,techStack,loomVideoId,liveLink,githubLink,slug,image,color,category}:Project){return <article className="project-card"><ProjectVideo {...{title,image,loomVideoId,color}}/><div className="project-meta"><p className="eyebrow">{category}</p><Link href={`/project/${slug}`} aria-label={`View ${title} case study`} className="project-title"><h3>{title}</h3><span><ArrowUpRight size={24}/></span></Link><p className="project-description">{description}</p><div className="tags">{techStack.map(t=><span key={t}>{t}</span>)}</div>{(liveLink||githubLink)&&<div className="project-links">{liveLink&&<a href={liveLink} target="_blank" rel="noreferrer">Live site <ExternalLink size={14}/></a>}{githubLink&&<a href={githubLink} target="_blank" rel="noreferrer">Source <Code2 size={14}/></a>}</div>}</div></article>}
