export const profile={name:'Ahmed Esmail',email:'ahmedesmailofficial01@gmail.com',github:'https://github.com/ahmedesmail01',linkedin:'https://linkedin.com/in/ahmed-esmail-a28152239'};
export type Project={slug:string;title:string;description:string;techStack:string[];category:string;image:string;color:string;loomVideoId?:string;liveLink?:string;githubLink?:string;overview:string;features:string[];sample:boolean};
export const projects:Project[]=[
{slug:'keybuilds',title:'KeyBuilds',description:'A new dimension in keyboard customization.',techStack:['Next.js 14','Supabase','Three.js'],category:'INTERACTIVE COMMERCE',image:'/images/keyboard.webp',color:'#b2a0fa',sample:true,overview:'A sample case study for an interactive mechanical keyboard configurator. The concept brings product exploration into three dimensions, connecting a responsive storefront to a configurable product experience.',features:['Explore a mechanical keyboard in 3D','Preview combinations of keycaps and finishes','Connect product configuration to a Supabase data model']},
{slug:'sky-events',title:'Sky Events',description:'An unforgettable first impression, before the event.',techStack:['Next.js','Vercel'],category:'EVENT EXPERIENCE',image:'/images/events.webp',color:'#bde4fa',sample:true,overview:'A sample digital invitation experience that gives an event its own destination. A mobile-first presentation brings the venue, schedule and invitation details together.',features:['Responsive digital invitations','Clear event information and guest journeys','A streamlined Next.js deployment on Vercel']},
{slug:'job-elite',title:'Job Elite',description:'Behind every great platform, a solid foundation.',techStack:['Backend architecture','CI/CD','Hostinger'],category:'BACKEND & DEVOPS',image:'/images/workspace.webp',color:'#f4a57b',sample:true,overview:'A sample infrastructure case study focused on the path from a development change to a production release. The proposed architecture separates staging and production and makes deployment repeatable.',features:['Separate staging and production environments','Automated build and release pipelines','Maintainable backend boundaries and configuration']},
{slug:'fittra-training',title:'Fittra Training',description:'Bringing learning, live sessions, and payments together.',techStack:['Next.js','Zustand','Zoom SDK','Stripe'],category:'LEARNING PLATFORM',image:'/images/learning.webp',color:'#d4fa78',sample:false,overview:'Part of the Fittra ecosystem: an interconnected suite of training, streaming and clinic applications. My work includes frontend development, state management, live-session integrations and payment-gated experiences.',features:['Learning interfaces with Zustand and Redux state management','Zoom SDK integration for live learning sessions','Payment and subscription journeys across the Fittra ecosystem']}
];
export const skills=[{title:'Frontend',items:['React.js','Next.js','Vue.js','TypeScript','Tailwind CSS','Redux Toolkit','Zustand']},{title:'Backend',items:['Node.js','NestJS','Java','Spring Boot','REST APIs','Laravel']},{title:'Enterprise & database',items:['PostgreSQL','ServiceNow','Oracle APEX','Docker','CI/CD','MongoDB']}];
export const services=[
{title:'Websites & landing pages',tag:'MAKE YOUR FIRST IMPRESSION COUNT',description:'Distinctive, responsive websites that turn your business into a clear and compelling digital experience.',items:['Business and personal websites','Conversion-focused landing pages','Multilingual & RTL experiences','Technical SEO and accessibility'],icon:'globe'},
{title:'E-commerce & subscriptions',tag:'FROM DISCOVERY TO CHECKOUT',description:'Commerce experiences that make finding, buying and managing products feel effortless.',items:['Product catalogs and storefronts','Checkout and payment integrations','Subscriptions and member access','Order management dashboards'],icon:'cart'},
{title:'LMS & learning platforms',tag:'BUILD A BETTER WAY TO LEARN',description:'Bring your courses, learners and live sessions into one connected platform.',items:['Courses and progress tracking','Zoom-powered live sessions','Paid content and memberships','Learner and instructor dashboards'],icon:'book'},
{title:'CRM & business portals',tag:'GIVE YOUR TEAM A CLEARER VIEW',description:'Custom tools that connect your customers, processes and business information.',items:['Customer and lead management','Role-based client portals','Reporting and data dashboards','Appointment and clinic workflows'],icon:'users'},
{title:'ERP modules & workflows',tag:'LESS MANUAL WORK. MORE CLARITY.',description:'Focused operational modules scoped around your existing systems and the way your team works.',items:['Inventory and order workflows','Approval and request management','ServiceNow catalog workflows','Oracle APEX forms and reports'],icon:'workflow'},
{title:'SaaS & custom applications',tag:'TAKE YOUR PRODUCT FROM IDEA TO LAUNCH',description:'End-to-end product development, with a thoughtful interface and an architecture that can evolve.',items:['MVP planning and implementation','Authentication and access control','Admin panels and customer journeys','Real-estate and event platforms'],icon:'layers'},
{title:'APIs & integrations',tag:'MAKE YOUR SYSTEMS WORK TOGETHER',description:'Reliable backends and integrations that connect your product to the tools it depends on.',items:['NestJS and Node.js REST APIs','PostgreSQL data modeling','Stripe, Paymob, Tabby & Tamara','Zoom, Google Maps and Auth0'],icon:'code'},
{title:'Performance & deployment',tag:'SHIP CONFIDENTLY. KEEP IMPROVING.',description:'Improve an existing application or create a dependable path from development to production.',items:['Frontend performance audits','Next.js migrations and refactoring','Docker and GitHub Actions CI/CD','Staging and production setup'],icon:'gauge'}
];
export const posts=[
{slug:'designing-payment-journeys',title:'The checkout is a journey, not a button.',category:'PRODUCT ENGINEERING',image:'/images/keyboard.webp',read:'4 min read',intro:'A payment integration touches far more than the final transaction. It shapes how customers discover a product, understand the price and recover when something goes wrong.',sections:[['Start before the payment form','Make the price, billing period and next step clear before asking for payment details. A predictable journey gives customers fewer reasons to hesitate.'],['Treat payment status as server-owned state','A successful redirect is not sufficient proof of payment. Verify the provider event on the server, handle duplicate notifications idempotently and only grant access after the payment status has been confirmed.'],['Design the recovery path','Declined payments, delayed notifications and abandoned checkouts are ordinary states. Give each one an understandable message and a safe way to continue.'],['Keep access in sync','Separate payment records from access rules so refunds, subscription changes and renewals can update the customer experience consistently.']]},
{slug:'frontend-that-scales',title:'A frontend that grows with your product.',category:'FRONTEND',image:'/images/workspace.webp',read:'3 min read',intro:'A scalable frontend starts with clear boundaries. Components, state and data fetching should each have a purpose that another developer can understand.',sections:[['Organize around the product','Group related features so a change to a learning flow or a checkout does not require searching across unrelated directories. Keep shared primitives small and predictable.'],['Give state an owner','Use local state for local interactions, a server-state cache for remote data and shared state only when multiple features actually need it. Avoid making every value global.'],['Keep the first load intentional','Load heavy embeds and specialized interactions only when needed. Reserve the dimensions of media so the layout remains stable while assets arrive.'],['Measure real journeys','Test the routes people actually use on slower devices. A fast landing page matters, but so do the forms, dashboards and transitions that follow it.']]},
{slug:'safer-release-pipelines',title:'From “works locally” to a reliable release.',category:'DEVOPS',image:'/images/events.webp',read:'3 min read',intro:'A deployment pipeline is most useful when it makes ordinary releases repeatable and recovery understandable.',sections:[['Separate your environments','Keep staging and production configuration distinct. Use staging to exercise integrations without modifying real customer data.'],['Build once, deploy deliberately','Create a versioned artifact, check that the build succeeds and keep a record of the version that was deployed. This makes a release traceable.'],['Handle secrets outside source control','Keep credentials in the environment or secret manager. Be deliberate about frontend environment variables: anything bundled into client code is visible to visitors.'],['Plan the rollback','Know which artifact was previously healthy and how to restore it. Treat database changes carefully because application rollback does not automatically undo a migration.']]}
];
