import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,ArrowUpRight,Check} from 'lucide-react';
import {projects} from '@/lib/content';
import {Header,Footer} from '@/components/site-shell';
import {ProjectVideo} from '@/components/video-project-card';
export function generateStaticParams(){return projects.map(p=>({projectSlug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{projectSlug:string}>}){const {projectSlug}=await params;const p=projects.find(p=>p.slug===projectSlug);return {title:p?.title??'Project not found',description:p?.description};}
export default async function ProjectPage({params}:{params:Promise<{projectSlug:string}>}){const {projectSlug}=await params;const p=projects.find(p=>p.slug===projectSlug);if(!p)notFound();const next=projects[(projects.indexOf(p)+1)%projects.length];return <><Header/><main className="wrap detail-page"><Link className="back-link" href="/#work"><ArrowLeft size={16}/> Back to selected work</Link><div className="detail-heading"><p className="eyebrow">{p.category} {p.sample?' / SAMPLE CASE STUDY':''}</p><h1>{p.title}<span className="lime">.</span></h1><p>{p.description}</p></div><ProjectVideo {...p} large/><div className="detail-body"><aside><p className="eyebrow">THE STACK</p><div className="tags">{p.techStack.map(t=><span key={t}>{t}</span>)}</div><p className="media-note">Illustrative cover. Project walkthrough coming soon.</p>{p.liveLink&&<a className="text-link" href={p.liveLink} target="_blank" rel="noreferrer">Visit live site <ArrowUpRight size={18}/></a>}{p.githubLink&&<a className="text-link" href={p.githubLink} target="_blank" rel="noreferrer">View source <ArrowUpRight size={18}/></a>}</aside><article><p className="eyebrow">OVERVIEW</p><h2>{p.sample?'The concept.':'The work.'}<br/><span className="serif">The details that matter.</span></h2><p>{p.overview}</p><h3>{p.sample?'Proposed experience':'Areas of contribution'}</h3><ul className="feature-list">{p.features.map(f=><li key={f}><Check size={18}/>{f}</li>)}</ul><Link className="pill" href="/#contact">Build something like this <ArrowUpRight size={18}/></Link></article></div><Link className="next-project" href={`/project/${next.slug}`}><div><p className="eyebrow">NEXT PROJECT</p><h2>{next.title}</h2></div><ArrowUpRight size={55}/></Link></main><Footer/></>}
